# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('e_mail', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('education', models.CharField(max_length=500)),
                ('languages_skills', models.CharField(max_length=200)),
                ('skills', models.TextField()),
                ('additional_information', models.TextField()),
            ],
        ),
    ]
