# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='age',
        ),
        migrations.AddField(
            model_name='resume',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
