# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20170303_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_level', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='languages_skills',
        ),
        migrations.AddField(
            model_name='languages',
            name='languages_levels',
            field=models.ManyToManyField(through='resume.LanguageLevel', to='resume.Resume'),
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Languages'),
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
