# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-16 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20170309_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('e_mail', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('skype', models.CharField(blank=True, max_length=30, null=True)),
                ('education', models.CharField(max_length=500)),
                ('skills', models.TextField()),
                ('additional_information', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='languages',
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Person'),
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AddField(
            model_name='person',
            name='languages',
            field=models.ManyToManyField(through='resume.LanguageLevel', to='resume.Language'),
        ),
    ]
