# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-14 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20170309_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skype',
            field=models.CharField(default='skype_id', max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
