# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20170303_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='birthday',
        ),
        migrations.AddField(
            model_name='resume',
            name='age',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
