# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20170303_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='age',
        ),
        migrations.AddField(
            model_name='resume',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
