# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-09 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20170309_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='languages',
            name='languages_levels',
        ),
        migrations.RenameField(
            model_name='languagelevel',
            old_name='language_level',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='languagelevel',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Language'),
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.AddField(
            model_name='resume',
            name='anguages',
            field=models.ManyToManyField(through='resume.LanguageLevel', to='resume.Language'),
        ),
    ]
