# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('e_mail', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('skype', models.CharField(blank=True, max_length=30, null=True)),
                ('education', models.CharField(max_length=500)),
                ('skills', models.TextField()),
                ('additional_information', models.TextField()),
                ('languages', models.ManyToManyField(through='cv.LanguageLevel', to='cv.Language')),
            ],
        ),
        migrations.AddField(
            model_name='languagelevel',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Person'),
        ),
    ]
